x-rails-env: &rails_env
  HOST: "0.0.0.0"
  BUNDLE_PATH: /bundle

services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./.bashrc:/root/.bashrc:ro,cached
      - ..:/workspace:cached
      - bundle_cache:/bundle
    ports:
      - "3000:3000"
    command: sleep infinity
    environment:
      <<: *rails_env

volumes:
  bundle_cache:
