default: &default
  adapter: sqlite3
  timeout: 5000
  default_transaction_mode: IMMEDIATE
  pragmas:
    foreign_keys: "ON"

development:
  primary:
    <<: *default
    database: storage/development_primary.sqlite3
    extensions:
      - <%= SQLean::UUID.to_path %>
  cache:
    <<: *default
    database: storage/development_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    adapter: sqlite3
    database: storage/development_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    adapter: sqlite3
    database: storage/development_cable.sqlite3
    migrations_paths: db/cable_migrate

test:
  <<: *default
  database: storage/test_primary.sqlite3
  extensions:
    - <%= SQLean::UUID.to_path %>

production:
  primary:
    <<: *default
    database: storage/production_primary.sqlite3
    extensions:
      - <%= SQLean::UUID.to_path %>
  cache:
    <<: *default
    database: storage/production_cache.sqlite3
    migrations_paths: db/cache_migrate
  queue:
    <<: *default
    database: storage/production_queue.sqlite3
    migrations_paths: db/queue_migrate
  cable:
    <<: *default
    database: storage/production_cable.sqlite3
    migrations_paths: db/cable_migrate
