default: &default
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12

  import_market_data:
    class: "ImportMarketDataJob"
    queue: "scheduled"
    args: [{ mode: 'full', clear_cache: false }] 
    schedule: "0 22 * * 1-5" # 5:00 PM EST / 6:00 PM EDT (NY time) Monday through Friday
    description: "Imports market data daily at 5:00 PM EST (1 hour after market close)"


production:
  <<: *default
  clean_syncs:
    schedule: "0 * * * *" # every hour
    class: "SyncCleanerJob"
    queue: "scheduled"
    description: "Cleans up stale syncs"

  run_security_health_checks:
    schedule: "0 2 * * 1-5" # 2:00 AM EST / 3:00 AM EDT (NY time) Monday through Friday
    class: "SecurityHealthCheckJob"
    queue: "scheduled"
    description: "Runs security health checks to detect issues with security data"
        
  seed_dump:
    class: "SeedDumpJob"
    queue: "scheduled"
    description: "Runs seed dump manually"
    schedule: "every month"
    
development:
  <<: *default